export const mockClassifieds = [
  {
    id: 0,
    title: "Vintage Wooden Desk - Perfect Condition!",
    description:
      "BSelling a beautiful vintage wooden desk in excellent condition. Crafted from solid oak, this desk features four drawers, a smooth writing surface, and classic brass handles. Ideal for home offices, students, or collectors. No scratches or damage. Dimensions: 120cm x 60cm x 75cm. Pickup in Dublin city centre. €150 or nearest offer. Email for details! 📩",
    section: "Furniture",
    price: 300,
    email: "antiques@example.com",
    img: "https://picsum.photos/400/226",
  },
  {
    id: 1,
    title: "Antique Sofa",
    description:
      "Beautiful vintage piece, recently restored. Perfect for a living room centerpiece. Beautiful vintage piece, recently restored. Perfect for a living room centerpiece.",
    section: "Furniture",
    price: 300,
    email: "antiques@example.com",
    img: "https://picsum.photos/400/225",
  },
  {
    id: 2,
    title: "Graphic Designer Wanted",
    description:
      "Part-time freelance opportunity. Looking for a creative individual to join our team.",
    section: "Jobs",
    price: 0,
    email: "jobs@creativeco.com",
    img: "https://picsum.photos/226/401",
  },
  {
    id: 3,
    title: "Golden Retriever Puppies",
    description:
      "Adorable, playful puppies looking for a loving home. Vaccinated and ready to go.",
    section: "Pets",
    price: 400,
    email: "pups@puppy.pup",
    img: "https://picsum.photos/401/226",
  },
  {
    id: 4,
    title: "Lawn Mowing Services",
    description: "Affordable lawn care services available for all yard sizes.",
    section: "Services",
    price: 25,
    email: "lawncare@local.com",
    img: "https://picsum.photos/400/400",
  },
  {
    id: 5,
    title: "Music Lessons",
    description:
      "Piano and guitar lessons for beginners and intermediates. Flexible scheduling.",
    section: "Education",
    price: 30,
    email: "music@example.com",
    img: "https://picsum.photos/401/401",
  },
  {
    id: 6,
    title: "Lost Cat",
    description:
      "Black cat with green eyes. Last seen near Main Street. Reward offered.",
    section: "Lost and Found",
    price: 0,
    email: "lostpets@example.com",
    img: "https://picsum.photos/225/400",
  },
  {
    id: 7,
    title: "Antique Sofa",
    description:
      "Beautiful vintage piece, recently restored. Perfect for a living room centerpiece.",
    section: "Furniture",
    price: 300,
    email: "antiques@example.com",
    img: "https://picsum.photos/402/226",
  },
  {
    id: 8,
    title: "Used Bicycle",
    description: "A used bicycle in decent condition.",
    section: "Sports",
    price: 50,
    email: "sports@example.com",
    img: "https://picsum.photos/403/226",
  },
  {
    id: 9,
    title: "Old Books",
    description: "A collection of old books.",
    section: "Books",
    price: 20,
    email: "books@example.com",
    img: "https://picsum.photos/226/400",
  },
  {
    id: 10,
    title: "Kitchen Utensils",
    description: "Various kitchen utensils.",
    section: "Household",
    price: 15,
    email: "household@example.com",
    img: "https://picsum.photos/225/400",
  },
  {
    id: 11,
    title: "Office Chair",
    description: "Comfortable office chair.",
    section: "Furniture",
    price: 75,
    email: "furniture@example.com",
    img: "https://picsum.photos/401/400",
  },
  {
    id: 12,
    title: "Winter Jacket",
    description: "Warm winter jacket.",
    section: "Clothing",
    price: 40,
    email: "clothing@example.com",
    img: "https://picsum.photos/400/401",
  },
  {
    id: 13,
    title: "Garden Tools",
    description: "Set of garden tools.",
    section: "Gardening",
    price: 25,
    email: "gardening@example.com",
    img: "https://picsum.photos/402/225",
  },
  {
    id: 14,
    title: "Laptop",
    description: "Used laptop in working condition.",
    section: "Electronics",
    price: 200,
    email: "electronics@example.com",
    img: "https://picsum.photos/403/224",
  },
  {
    id: 15,
    title: "Dining Table",
    description: "Wooden dining table.",
    section: "Furniture",
    price: 150,
    email: "furniture@example.com",
    img: "https://picsum.photos/400/225",
  },
  {
    id: 16,
    title: "Running Shoes",
    description: "Pair of running shoes.",
    section: "Sports",
    price: 30,
    email: "sports@example.com",
    img: "https://picsum.photos/406/227",
  },
  {
    id: 17,
    title: "Baby Stroller",
    description: "Baby stroller in good condition.",
    section: "Baby",
    price: 100,
    email: "baby@example.com",
    img: "https://picsum.photos/406/229",
  },
  {
    id: 18,
    title: "Smartphone",
    description: "Used smartphone.",
    section: "Electronics",
    price: 150,
    email: "electronics@example.com",
    img: "https://picsum.photos/404/224",
  },
  {
    id: 19,
    title: "Coffee Maker",
    description: "Electric coffee maker.",
    section: "Appliances",
    price: 35,
    email: "appliances@example.com",
    img: "https://picsum.photos/401/223",
  },
  {
    id: 20,
    title: "Desk Lamp",
    description: "LED desk lamp.",
    section: "Furniture",
    price: 20,
    email: "furniture@example.com",
    img: "https://picsum.photos/402/224",
  },
  {
    id: 21,
    title: "Yoga Mat",
    description: "Non-slip yoga mat.",
    section: "Sports",
    price: 15,
    email: "sports@example.com",
    img: "https://picsum.photos/400/225",
  },
  {
    id: 22,
    title: "Blender",
    description: "Kitchen blender.",
    section: "Appliances",
    price: 25,
    email: "appliances@example.com",
    img: "https://picsum.photos/405/220",
  },
  {
    id: 23,
    title: "Dog Leash",
    description: "Durable dog leash.",
    section: "Pets",
    price: 10,
    email: "pets@example.com",
    img: "https://picsum.photos/390/230",
  },
  {
    id: 24,
    title: "Board Games",
    description: "Collection of board games.",
    section: "Toys",
    price: 30,
    email: "toys@example.com",
    img: "https://picsum.photos/410/215",
  },
];
