name: Custom GitHub Pages Deploy

on:
  push:
    branches:
      - main # or whatever branch you are using for your GitHub Pages source

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace placeholders in js/sbClient.js
        run: |
          sed -i 's/{{SUPABASE_URL}}/${{ secrets.SUPABASE_URL }}/g' ./js/sbClient.js
          sed -i 's/{{SUPABASE_ANON_KEY}}/${{ secrets.SUPABASE_ANON_KEY }}/g' ./js/sbClient.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
